---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - kafkapp
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
